---
- name: test
  hosts: all
  become: true
  tasks: 
    - name: httpd install
      yum: 
        name: httpd
        state: present
        
    - name: start and enable httpd
      service: 
        name: httpd
        state: started
        enabled: true
